// Commands the frontend is allowed to call. tauri-plugin generates the matching
// `allow-*` / `deny-*` permissions under permissions/autogenerated/ at build time;
// permissions/default.toml bundles them into the `bg-location:default` set that
// the app's capability references.
const COMMANDS: &[&str] = &["start_tracking", "stop_tracking"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .build();
}
